:PROPERTIES:
:ID:       87d3c192-5ea3-4424-b598-4cabdcf89ffc
:END:
#+title: Engineering as a Christian Vocation
:DRAWER:
#+subtitle: Fall 2024
#+author:
#+filetags: :article:
#+latex_class: article
#+latex_class_options: [11pt]
#+latex_header: \usepackage[left=0.75in, right=0.75in, top=0.75in, bottom=0.75in]{geometry}
#+bibliography: ~/org/biblio.bib
#+latex_header: \usepackage{biblatex}
#+options: toc:nil num:nil
#+latex_header_extra: \usepackage{mlmodern}
#+description:
#+keywords:
#+latex_engraved_theme:
#+latex_compiler: pdflatex
#+cite_export: biblatex
#+date:
#+latex_header: \usepackage{titlesec}
#+latex_header: \titleformat{\section}[block]{\Large\bfseries\filcenter}{}{1em}{}
#+latex_header: \let\oldsection\section
#+latex_header: \renewcommand\section{\clearpage\oldsection}
:END:
* Introduction
#+begin_center
*Faith and Vocation as Practitioners of Engineering, Computer Science, and
 Technology*
#+end_center

/"Whether you are a student or a seasoned professional, many Christians working
in technical areas struggle with engaging their faith in the world of
technology. Perhaps you never thought about how your faith might inform your
work in technology. Perhaps you feel a disconnect between your daily
professional life and your Christian spiritual walk. The development of
technology through science and engineering has always been a cultural activity
with religious implications, but its direction is set by the human heart.
Developing and using technology is one way we love God and our neighbor, and
more fully witness to the gospel of Jesus Christ for the entire world."/
#+begin_flushright
From /A Christian Field Guide to Technology for Engineers and Designers/ by
Ethan Brue, Derek Schuurman, and Steven Vanderleest
#+end_flushright

The primary question driving this discussion group is, /What is the role of a
Christian in a technological vocation?/ Modernity seems to be telling us that
science, technology, and engineering are somehow opposed to faith. Furthermore,
to many, the influence of technology and "science" are the primary reasons for
abandoning their faith. However, many feel called to engage with technology, not
simply as an end user, but a creator, practitioner, designer, and engineer.


* Schedule Overview
** Week 1
*_Subject: The Technological Frame_*

/“Therefore everyone who hears these words of mine and puts them into practice
is like a wise man who built his house on the rock. The rain came down, the
streams rose, and the winds blew and beat against that house; yet it did not
fall, because it had its foundation on the rock. But everyone who hears these
words of mine and does not put them into practice is like a foolish man who
built his house on sand. The rain came down, the streams rose, and the winds
blew and beat against that house, and it fell with a great crash.”/ Matthew
7:24-27

Can we build our understanding of the technological vocation on rock?
*** Readings
- /What Frames What?/ by Richard Horner /Reconsiderations/ Vol 4, #5 October
  2005
- /Five Things We Need to Know About Technological Change/ by Neil Postman,
  Lecture Given in March 1998
** Week 2
*_Subject: A Christian Framing of Technology_*
*** Readings
- /The Computer Scientist as Toolsmith II/ by Fred Brooks, Communications with
  the ACM, March 1996
** Week 3
*_Subject:_*
*** Readings
-
** Week 4
*_Subject: Responsible Technology_*

/"Whatever you do, work at it with all your heart, as working for the Lord, not
for human masters, since you know that you will receive an inheritance from
the Lord as a reward. It is the Lord Christ you are serving."/ Colossians 3:23-24
*** Readings
-
* Week 1
** Readings
** Discussion Topics
