:PROPERTIES:
:ID:       87d3c192-5ea3-4424-b598-4cabdcf89ffc
:END:
#+title: S.T.E.M. as a Christian Vocation
:DRAWER:
#+subtitle: Fall 2024
#+author:
#+filetags: :article:
#+latex_class: article
#+latex_class_options: [11pt]
#+latex_header: \usepackage[left=0.75in, right=0.75in, top=0.75in, bottom=0.75in]{geometry}
#+bibliography: ~/org/biblio.bib
#+latex_header: \usepackage{biblatex}
#+latex_header: \usepackage{mdframed}
#+options: toc:nil num:nil
#+latex_header_extra: \usepackage{mlmodern}
#+description:
#+keywords:
#+latex_engraved_theme:
#+latex_compiler: pdflatex
#+cite_export: biblatex
#+date:
#+latex_header: \usepackage{titlesec}
#+latex_header: \titleformat{\section}[block]{\Large\bfseries\filcenter}{}{1em}{}
#+latex_header: \let\oldsection\section
#+latex_header: \renewcommand\section{\clearpage\oldsection}
:END:
* Introduction
#+begin_center
*Faith and Vocation as Practitioners of Engineering, Computer Science, and
 Technology*
#+end_center

/"Whether you are a student or a seasoned professional, many Christians working
in technical areas struggle with engaging their faith in the world of
technology. Perhaps you never thought about how your faith might inform your
work in technology. Perhaps you feel a disconnect between your daily
professional life and your Christian spiritual walk. The development of
technology through science and engineering has always been a cultural activity
with religious implications, but its direction is set by the human heart.
Developing and using technology is one way we love God and our neighbor, and
more fully witness to the gospel of Jesus Christ for the entire world."/

#+begin_flushright
From /A Christian Field Guide to Technology for Engineers and Designers/ by
Ethan Brue, Derek Schuurman, and Steven Vanderleest
#+end_flushright

The primary question driving this discussion group is, /What does it mean to
follow Christ in a technological vocation?/ Modernity seems to be telling us that
science, technology, and engineering are somehow opposed to faith. Furthermore,
to many, the influence of technology and "science" are the primary reasons for
abandoning their faith. However, many feel called to engage with technology, not
simply as an end user, but a creator, practitioner, designer, and engineer.


* Schedule Overview
** Week 1
*_Subject: The Technological Frame_*
#+attr_latex: :options [nobreak=true]
#+begin_mdframed options [nobreak=true]
/“Therefore everyone who hears these words of mine and puts them into practice
is like a wise man who built his house on the rock. The rain came down, the
streams rose, and the winds blew and beat against that house; yet it did not
fall, because it had its foundation on the rock. But everyone who hears these
words of mine and does not put them into practice is like a foolish man who
built his house on sand. The rain came down, the streams rose, and the winds
blew and beat against that house, and it fell with a great crash.”/ Matthew
7:24-27
#+end_mdframed

Can we build our understanding of the technological vocation on rock?
*** Readings
- /What Frames What?/ by Richard Horner /Reconsiderations/ Vol 4, #5 October
  2005
- /Five Things We Need to Know About Technological Change/ by Neil Postman,
  Lecture Given in March 1998
- /A Christian Field Guide to Technology for Engineers and Designers/, Chapters
  2 & 3, by Ethan Brue, Derek Schuurman, and Steven Vanderleest
** Week 2
*_Subject: A Secular Framing of Ethics_*
#+attr_latex: :options [nobreak=true]
#+begin_mdframed nobreak=true
/"Do not love the world or anything in the world. If anyone loves the world,
love for the Father is not in them. For everything in the world—the lust
of the flesh, the lust of the eyes, and the pride of life—comes not from the
Father but from the world. The world and its desires pass away, but whoever
does the will of God lives forever."/ 1 John 2:15-17

#+end_mdframed
*** Readings
- /Ethics in the Age of Disruptive Technology, Appendix 1/2 - Examples of
  Technology Ethics and Responsible Technology Practices & ITEC Principles and
  How to Use Them: Anchoring, Guiding, Specifying, Action/ by Intstitute for
  Technology, Ethics, and Culture
- /Ethics in Technology Practice/ by Shannon Vallor, Iring Raicu, and Brian
  Green. The Markkula Center for Applied Ethics at Santa Clara University
- /Code of Ethics for Engineers/ National Society of Professional Engineers
- /EGS 4034 Syllabus - Engineering Ethics/ University of Florida
** Week 3
*_Subject: A Christian Framing of Ethics_*
#+attr_latex: :options [nobreak=true]
#+begin_mdframed
/"Do not conform to the pattern of this world, but be transformed by the
renewing of your mind. Then you will be able to test and approve what God’s will
is—his good, pleasing and perfect will."/ Romans 12:2 @@latex:\newline@@
@@latex:\noindent@@ /"Your hands made me and formed me; give me understanding to
learn your commands."/ Psalm 119:73
#+end_mdframed
*** Readings
- /The Computer Scientist as Toolsmith II/ by Fred Brooks, Communications with
  the ACM, March 1996
- /A Christian Field Guide to Technology for Engineers and Designers/, Chapters
  5 & 6, by Ethan Brue, Derek Schuurman, and Steven Vanderleest

** Week 4
*_Subject: Putting it Into Practice_*
#+attr_latex: :options [nobreak=true]
#+begin_mdframed
/"Whatever you do, work at it with all your heart, as working for the Lord, not
for human masters, since you know that you will receive an inheritance from the
Lord as a reward. It is the Lord Christ you are serving."/ Colossians 3:23-24
#+end_mdframed
*** Readings
- /A Christian Field Guide to Technology for Engineers and Designers/, Chapter
  9, by Ethan Brue, Derek Schuurman, and Steven Vanderleest
* Week 1
#+begin_center
@@latex:\large@@ *_The Technological Frame_*
#+end_center
#+begin_mdframed
/"I never said a word against eminent men of science. What I complain of is a
vague popular philosophy which supposes itself to be scientific when it is
really nothing but a sort of new religion and an uncommonly nasty one. When
people talked about the fall of man, they knew they were talking about a
mystery, a thing they didn’t understand. Now they talk about the survival of the
fittest: they think they do understand it, whereas they have not merely no
notion, they have an elaborately false notion of what the words mean."/

@@latex:\hfill@@ G.K. Chesterton, /The Club of Queer Trades/ (1905)
#+end_mdframed
** Readings
1. /What Frames What?/ by Richard Horner
2. /Five Things We Need to Know About Technological Change/ by Neil Postman
3. /A Christian Field Guide to Technology for Engineers and Designers/, Chapters
   2 & 3, by Ethan Brue, Derek Schuurman, and Steven Vanderleest
** Discussion Topics
- What frame does modern society inhabit? Is it Christian? Post-Christian?
  Modern? Utilitarian? Religious? Anti-religious? Technological?
- How does our frame dictate our actions?
- What serves what? Does technology serve us, or are we molded to serve
  technology?
- Technology as an /ecological/ (not /additive/) change.
* Week 2
#+begin_center
@@latex:\large@@ *_A Secular Framing of Ethics_*
#+end_center
#+begin_mdframed options
/"Mr. Wells, however, is not quite clear enough of the narrower scientific outlook
to see that there are some things which actually ought not to be scientific. He
is still slightly affected with the great scientific fallacy; I mean the habit
of beginning not with the human soul, which is the first thing a man learns
about, but with some such thing as protoplasm, which is about the last. The one
defect in his splendid mental equipment is that he does not sufficiently allow
for the stuff or material of men. In his new Utopia he says, for instance, that
a chief point of the Utopia will be a disbelief in original sin. If he had begun
with the human soul—that is, if he had begun on himself—he would have found
original sin almost the first thing to be believed in."/

@@latex:\hfill@@ G.K. Chesterton, /Heretics/ (1905)
#+end_mdframed
** Readings
1. /Ethics in the Age of Disruptive Technology, Appendix 1/2/ by Intstitute for
   Technology, Ethics, and Culture
2. /Ethics in Technology Practice/ by Shannon Vallorm, Iring Raicu, and Brian
   Green
3. /Code of Ethics for Engineers/ by National Society of Professional Engineers
4. /EGS 4034 Syllabus - Engineering Ethics/, University of Florida
** Discussion Topics
- ITEC listed Microsoft, IBM, and Google as /exemplars/ of an "ethical company".
  Do you agree? Why or why not?
- Most modern ethical frameworks seem to revolve around
  utilitarianism/consequentialism
  (https://plato.stanford.edu/entries/consequentialism/). That is, actions
  should be judged on their outcome, and the judging criteria is the /net
  good/utility/happiness/ as a result. How ought a Christian think about this?

* Week 3
#+begin_center
@@latex:\large@@ *_A Christian Framing of Ethics_*
#+end_center
#+begin_mdframed options
/"Modern masters of science are much impressed with the need of beginning all
inquiry with a fact. The ancient masters of religion were quite equally
impressed with that necessity. They began with the fact of sin—a fact as
practical as potatoes. Whether or not man could be washed in miraculous waters,
there was no doubt at any rate that he wanted washing."/

@@latex:\hfill@@ G.K. Chesterton, /Orthodoxy/ (1908) @@latex:\newline@@

@@latex:\noindent@@ /"Christianity is an event. There is no other word to indicate its nature, neither the word
law, nor the words ideology, concept, or plan. Christianity is not a religious doctrine, a
series of moral laws or a collection of rites. Christianity is a fact, an event."/

@@latex:\hfill@@ Luigi Giussani, /Generating Traces in the History of the World/ (2010)
#+end_mdframed
** Readings
1. /The Computer Scientist as Toolsmith II/ by Fred Brooks
2. /A Christian Field Guide to Technology for Engineers and Designers/, Chapters
  5 & 6, by Ethan Brue, Derek Schuurman, and Steven Vanderleest
3. Matthew 5-7 (The Sermon on the Mount)
** Discussion Topics
- The revival of virtue ethics
  (https://plato.stanford.edu/entries/ethics-virtue/) in modern times has seen a
  resurgence among Christian thinkers. How does this interact with technology?
- What are the main differences between Christian ethics and secular ethics?
* Week 4
#+begin_center
@@latex:\large@@ *_Putting it Into Practice_*
#+end_center

#+begin_mdframed
/"But I have only taken this as the first and most evident case of the general
truth: that the great ideals of the past failed not by being outlived (which
must mean over-lived), but by not being lived enough. Mankind has not passed
through the Middle Ages. Rather mankind has retreated from the Middle Ages in
reaction and rout. The Christian ideal has not been tried and found wanting. It
has been found difficult; and left untried."/

@@latex:\hfill@@ G.K. Chesterton, /What's Wrong with the World/ (1910) @@latex:\newline@@

@@latex:\noindent@@ /"Once again I say: do not be proud. Do not be proud before
those lesser than you, nor before those greater than you. Do not despise those
who spurn you, slander you, revile you, or libel you. Do not despise atheists,
teachers of evil, materialists, or even the wicked, especially the good among
them, because there are many who are good among them even in our time. Remember
them in your prayers as follows: ‘Save, O Lord, those who have no one to pray
for them; also save those who don’t wish to pray to You.’ And add: ‘I am not
praying about them from my pride, Lord, for I myself am vile and worse than
everyone and everything.’ Love God’s common people; do not allow the flock to be
lured away by strangers, for if you fall asleep while in laziness or in your
squeamish pride or, worse, in your covetousness, then they will come from all
sides and lure away your flock. Teach the Gospel to the common people
incessantly....Avoid corruption. Do not come to love gold and silver, do not
hoard them....Believe and raise the banner. Hold it high..."/

@@latex:\hfill@@ Father Zosima in Fyodor Dostoevsky's /The Brothers Karamazov/ (1879)
#+end_mdframed
** Readings
1. /A Christian Field Guide to Technology for Engineers and Designers/, Chapter
  9, by Ethan Brue, Derek Schuurman, and Steven Vanderleest
** Discussion Topics
- How ought a Christian act within the institution?
- What are some tangible ways to stay rooted in the beatific vision while
  employed in a highly technical role?
- How to not be discouraged and find "the good among them", as Father Zosima
  (Fyodor Dostoevsky) mentions?
